# Generated by Django 3.2.4 on 2021-07-02 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fragments',
            fields=[
                ('kind', models.CharField(max_length=50)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('unique_id', models.AutoField(default=0, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Models',
            fields=[
                ('name', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('classes', models.IntegerField(blank=True, null=True)),
                ('relations', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Labels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField()),
                ('fragment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='labeling.fragments')),
            ],
        ),
        migrations.AddField(
            model_name='fragments',
            name='model',
            field=models.ForeignKey(blank=True, db_column='model', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='labeling.models'),
        ),
    ]
