# Generated by Django 3.2.4 on 2021-07-07 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0002_rename_labels_label'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fragments',
            new_name='Fragment',
        ),
        migrations.RenameModel(
            old_name='Models',
            new_name='Model',
        ),
    ]
