# Generated by Django 3.2.4 on 2021-07-12 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0003_auto_20210707_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='fragment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='labeling.fragment'),
        ),
    ]
