# Generated by Django 3.2.4 on 2021-07-23 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0004_alter_label_fragment'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='in_english',
            field=models.BooleanField(default=True),
        ),
    ]
