# Generated by Django 3.2.4 on 2021-09-13 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0005_label_in_english'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='validated',
            field=models.BooleanField(default=False),
        ),
    ]
